"""Data models for code-context-agent."""

from code_context_agent.models.base import FrozenModel, StrictModel
from code_context_agent.models.output import (
    AnalysisConfidence,
    AnalysisResult,
    ArchitecturalPattern,
    ArchitecturalRisk,
    AreaRiskProfile,
    BusinessLogicItem,
    CalibratedJudgment,
    ChangeVerdict,
    ConsistencyReport,
    ContractConsumer,
    CrossRepoImpact,
    DecisionBoundary,
    GeneratedFile,
    IndexFreshness,
    PatternViolation,
    PhaseTiming,
    ReviewerRecommendation,
    RiskProfile,
    RiskSnapshot,
    ServiceContract,
    TemporalRiskProfile,
    VerdictResponse,
    VerdictSignal,
)

__all__ = [
    "AnalysisConfidence",
    "AnalysisResult",
    "ArchitecturalPattern",
    "ArchitecturalRisk",
    "AreaRiskProfile",
    "BusinessLogicItem",
    "CalibratedJudgment",
    "ChangeVerdict",
    "ConsistencyReport",
    "ContractConsumer",
    "CrossRepoImpact",
    "DecisionBoundary",
    "FrozenModel",
    "GeneratedFile",
    "IndexFreshness",
    "PatternViolation",
    "PhaseTiming",
    "ReviewerRecommendation",
    "RiskProfile",
    "RiskSnapshot",
    "ServiceContract",
    "StrictModel",
    "TemporalRiskProfile",
    "VerdictResponse",
    "VerdictSignal",
]
